### PR TITLE
pipe, user, channel setproperty segfault solved; Build.sh and Makefiles restructured

### PR DESCRIPTION
**Pull request by verpeteren**
Please review this all.

### CODE REVIEW

**Comment by ptejada** [comment]
Cool, i'll try this pull request myself.

**Comment by ptejada** [comment]
Nice updates, seems like you know your way around the source code pretty well. Tested this patch with an alternative [client framework](https://github.com/ptejada/ApePubSub/) that i've been working on without any errors. That `Ape.system()` method can be very handy indeed.

On a side note or request, is it possible to implement the JavaScript `eval()` function in the server side? The idea is that one could get access to the objects and their methods during run time or even build a console with it where one can inject or call any object method on demand, for developing and debugging purposes of course.

**Comment by ptejada** [comment]
At least the cleaner Build Process of this pull request should merged.

**Comment by lcharette** [comment]
I didn't test all changes, but it looks good. The merge have been done.

**Pull request merged**
