### PR TITLE
New "move" demo.

### PR DESCRIPTION
**Pull request by lcharette**

### CODE REVIEW

**Comment by lcharette** [comment]
FYI, this is for the website

**Comment by ptejada** [comment]
And onced this pull request is merged, will it go live to the website?

**Comment by lcharette** [comment]
Not automatically yet.

**Comment by lcharette** [comment]
I don't have access to the repo settings to setup a pull hook to update the website automatically, but I could setup a crontab to update the website periodically.

**Comment by ptejada** [comment]
Hey,

Didn't the hold demo had a box where you could send text messages?

**Comment by lcharette** [comment]
Yes indeed. I forgot to explain on this : 

I could have include it (not a big work), but I didn't implement that function because I thought it didn't meet the point of the demo. There's already the chat demo to understand how to create a chat (it's the same APE code more or less. The DOM manipulation are different).

**Pull request merged**
