### PR TITLE
MySQL bug correction

### PR DESCRIPTION
**Pull request by lcharette**
See commit description for details.

### CODE REVIEW

**Comment by paraboul** [comment]
Thanks Louis. It's now merged.

**Comment by lcharette** [comment]
Do you think it would be a good idea to create a new tag on GitHub for those changes? I guess it would be easier to bring support on the Google Group for people asking about MySQL support. 

The version number could also be changed in main.h and/or in the "infos_module" of libape-spidermonkey.c

**Comment by paraboul** [comment]
A good thing would be to create a binary package for i386, x86-64, OSX.

**Comment by lcharette** [comment]
I won't able to help for this one.

**Pull request merged**
